# Model Dockerfile
FROM python:3.8

WORKDIR /app

# Ensure your pickle files are copied here
COPY popular.pkl pt.pkl books.pkl similarity_scores.pkl /app/

# Set the command to run the application
CMD ["python", "app.py"]
